extends Node

var pokemonTitle = {
	GameManager.pokemon.Timberry: "Berry Pup Critter",
	GameManager.pokemon.Howliage: "Berry Wolf Critter",
	GameManager.pokemon.Botanine: "Large Foliage Critter",
	GameManager.pokemon.Pilfetch: "Sneaking Bird Critter",
	GameManager.pokemon.Criminalis: "Thieving Bird Critter",
	GameManager.pokemon.Geckrow: "Small Gecko Critter",
	GameManager.pokemon.Goanopy: "Small Lizard Critter",
	GameManager.pokemon.Varanitor: "Leaf Lizard Critter",
	GameManager.pokemon.Sligment: "Slow Moving Critter",
	GameManager.pokemon.Viscolor: "Impenetrable Critter",
	GameManager.pokemon.Gelescent: "Sturdy Worm Critter",
	GameManager.pokemon.Pasturlo: "Small Sheep Critter",
	GameManager.pokemon.Brambull: "Leafy Ram Critter",
	GameManager.pokemon.Maizotaur: "Ferocious Critter",
	GameManager.pokemon.Baoby: "Sprouting Critter",
	GameManager.pokemon.Baobaraffe: "Mud Giraffe Critter",
	GameManager.pokemon.Varmot: "Rabid Rat Critter",
	GameManager.pokemon.Merlicun: "Small Caterpillar Critter",
	GameManager.pokemon.Firomenis: "Awoken Moth Critter",
	GameManager.pokemon.Pompet: "Guardian Critter",
	GameManager.pokemon.Pomprim: "Forest Hero Critter",
	GameManager.pokemon.Saurky: "Water Lizard Critter",
	GameManager.pokemon.Crestaka: "Water Chicken Critter",
	GameManager.pokemon.Avipex: "Water Eagle Critter",
	GameManager.pokemon.Dampurr: "Shy Cat Critter",
	GameManager.pokemon.Rainther: "Inquizitive Panther Critter",
	GameManager.pokemon.Delugar: "Protective Panther Critter",
	GameManager.pokemon.Bonfur: "Teddy Bear Critter",
	GameManager.pokemon.Tindursa: "Aggresive Bear Critter",
	GameManager.pokemon.Sizzly: "Fire Bear Critter",
	GameManager.pokemon.Lollybog: "Creeping Slime Critter",
	GameManager.pokemon.Brewtrid: "Forgotten Potion Critter",
	GameManager.pokemon.Forbiddron: "Possesed Cauldron Critter",
	GameManager.pokemon.Kankwart: "Crystal Critter",
	GameManager.pokemon.Kankryst: "Transforming Rock Critter",
	GameManager.pokemon.Kankersaur: "Crystal Guardian Critter",
	GameManager.pokemon.Baulder: "Blind Lizard Critter",
	GameManager.pokemon.Dreadrock: "Blind Dog Critter",
	GameManager.pokemon.Tekagon: "Blind Dinosaur Critter",
	GameManager.pokemon.Minamai: "Small Fish Critter",
	GameManager.pokemon.Marelstorm: "Sharp Fish Critter",
	GameManager.pokemon.Dripwirt: "Shy Apparition Critter",
	GameManager.pokemon.Pourka: "Water Spirit Critter",
	GameManager.pokemon.Appalyp: "Small Coral Critter",
	GameManager.pokemon.Sycoral: "Dead Coral Critter",
	GameManager.pokemon.Nemesusa: "Gorgon Critter",
	GameManager.pokemon.Sillennium: "Island Guardian Critter"
}

var pokemonDescription = {
	GameManager.pokemon.Timberry: "Timberry loves to frollick in forests. It can often be found near berry bushes, getting a light snack. It is a common first critter among yougsters because of its cute appearance.",
	GameManager.pokemon.Howliage: "Howliage start to assume more responsibilities in its packs. It now has to gather berries for it's pack. This critter can often be seen eating berries, as they are its favorite snack.",
	GameManager.pokemon.Botanine: "Botanine is the leader of its pack. It takes care of the Timberrys and sends the howliage on missions. Without a botanine, the pack would quickly fall apart."
}
