extends Node

var pokemonTitle = {
	GameManager.pokemon.Timberry: "Berry Pup Critter",
	GameManager.pokemon.Howliage: "Berry Wolf Critter",
	GameManager.pokemon.Botanine: "Large Foliage Critter",
	GameManager.pokemon.Pilfetch: "Sneaking Bird Critter",
	GameManager.pokemon.Criminalis: "Thieving Bird Critter",
	GameManager.pokemon.Geckrow: "Small Gecko Critter",
	GameManager.pokemon.Goanopy: "Small Lizard Critter",
	GameManager.pokemon.Varanitor: "Leaf Lizard Critter",
	GameManager.pokemon.Sligment: "Slow Moving Critter",
	GameManager.pokemon.Viscolor: "Impenetrable Critter",
	GameManager.pokemon.Gelescent: "Sturdy Worm Critter",
	GameManager.pokemon.Pasturlo: "Small Sheep Critter",
	GameManager.pokemon.Brambull: "Leafy Ram Critter",
	GameManager.pokemon.Maizotaur: "Ferocious Critter",
	GameManager.pokemon.Baoby: "Sprouting Critter",
	GameManager.pokemon.Baobaraffe: "Mud Giraffe Critter",
	GameManager.pokemon.Varmot: "Rabid Rat Critter",
	GameManager.pokemon.Merlicun: "Small Caterpillar Critter",
	GameManager.pokemon.Firomenis: "Awoken Moth Critter",
	GameManager.pokemon.Pompet: "Guardian Critter",
	GameManager.pokemon.Pomprim: "Forest Hero Critter",
	GameManager.pokemon.Saurky: "Water Lizard Critter",
	GameManager.pokemon.Crestaka: "Water Chicken Critter",
	GameManager.pokemon.Avipex: "Water Eagle Critter",
	GameManager.pokemon.Dampurr: "Shy Cat Critter",
	GameManager.pokemon.Rainther: "Inquizitive Panther Critter",
	GameManager.pokemon.Delugar: "Protective Panther Critter",
	GameManager.pokemon.Bonfur: "Teddy Bear Critter",
	GameManager.pokemon.Tindursa: "Aggresive Bear Critter",
	GameManager.pokemon.Sizzly: "Fire Bear Critter",
	GameManager.pokemon.Lollybog: "Creeping Slime Critter",
	GameManager.pokemon.Brewtrid: "Forgotten Potion Critter",
	GameManager.pokemon.Forbiddron: "Possesed Cauldron Critter",
	GameManager.pokemon.Kankwart: "Crystal Critter",
	GameManager.pokemon.Kankryst: "Transforming Rock Critter",
	GameManager.pokemon.Kankersaur: "Crystal Guardian Critter",
	GameManager.pokemon.Baulder: "Blind Lizard Critter",
	GameManager.pokemon.Dreadrock: "Blind Dog Critter",
	GameManager.pokemon.Tekagon: "Blind Dinosaur Critter",
	GameManager.pokemon.Minamai: "Small Fish Critter",
	GameManager.pokemon.Marelstorm: "Sharp Fish Critter",
	GameManager.pokemon.Dripwirt: "Shy Apparition Critter",
	GameManager.pokemon.Pourka: "Water Spirit Critter",
	GameManager.pokemon.Appalyp: "Small Coral Critter",
	GameManager.pokemon.Sycoral: "Dead Coral Critter",
	GameManager.pokemon.Nemesusa: "Gorgon Critter",
	GameManager.pokemon.Sillennium: "Island Guardian Critter"
}

var pokemonDescription = {
GameManager.pokemon.Timberry: "Timberry loves to frolic in forests. It can often be found near berry bushes, enjoying a light snack. It is a common first critter among youngsters because of its cute appearance.",
GameManager.pokemon.Howliage: "Howliage starts to assume more responsibilities within its pack. It now has to gather berries for its pack. This critter can often be seen eating berries, as they are its favorite snack.",
GameManager.pokemon.Botanine: "Botanine is the leader of its pack. It takes care of the Timberries and sends the Howliage on missions. Without a Botanine, the pack would quickly fall apart.",
GameManager.pokemon.Pilfetch: "This sneaky little bird loves to steal nuts and berries from other critters. It can often be found in homes other than its own. Some experts think it might not even have a home of its own.",
GameManager.pokemon.Criminalis: "This bird is the ringleader of criminal activities. It is often seen in groups with Pilfetch, plundering stores of food. Many critters have learned of its evil deeds and stay away.",
GameManager.pokemon.Geckrow: "This adorable little critter is a fan favorite because of its cute appearance. It seems to always be happy, even if it just lost a battle. It likes to make its home in the mud.",
GameManager.pokemon.Goanopy: "This lizard likes to look out for the smaller critters in the forest. It protects them from fiends such as Pilfetch and Criminalis. It is hardly intimidating, but scares them away nonetheless.",
GameManager.pokemon.Varanitor: "This critter is the protector of the forest. It keeps everyone in check, even the Maizotaurs. Every critter in the forest has learned that what a Varanitor says goes.",
GameManager.pokemon.Sligment: "This little slug loves the rain. It is easier to spot when it is actively raining. It slithers around the forest floor and leaves trails that youngsters like to follow.",
GameManager.pokemon.Viscolor: "No longer an adorable slug, Viscolor's shell has grown. It is now fully encased in an impenetrable fortress. Many trainers are sad to see their Sligment go, but what comes next makes up for it.",
GameManager.pokemon.Gelescent: "Now emerged from its shell, Gelescent is fully grown. It has grown a pearl that is the source of its power. While it would fetch a high price at a shop, it is highly illegal to take it.",
GameManager.pokemon.Pasturlo: "Pasturlo seems to always be asleep. For this reason, it has become a symbol of rest and happiness. It lives a quiet life and is often seen in herds. They move around very little.",
GameManager.pokemon.Brambull: "Brambull is the more active version of Pasturlo. It is hard to tell if it is awake or not, so predators often stay away just in case. They protect the snoozing Pasturlo from any harm.",
GameManager.pokemon.Maizotaur: "These incredibly aggressive critters are the opposite of their predecessors. They are always running around and often get into fights. They protect their herd, but are often found in other places.",
GameManager.pokemon.Baoby: "This cute little guy can often be found near forest floors. It wanders around, looking for a nice ray of sunshine. After finding it, it will stay there for a while.",
GameManager.pokemon.Baobaraffe: "Now that its neck is taller, Baobaraffe can get more sun. This fills it with confidence, which often gets it in trouble. It is often seen stomping through crops for the fun of it.",
GameManager.pokemon.Varmot: "This weird little bipedal rat is a terror to farmers. Hordes of them can quickly come and ransack farms in mere minutes. There is not much that can be done once they show up and start eating.",
GameManager.pokemon.Merlicun: "This little caterpillar has more to it than meets the eye. Its cute caterpillar exterior gives way to a ferocious bug that eats everything in sight. It needs to eat for its metamorphosis.",
GameManager.pokemon.Firomenis: "The now-evolved Merlicun is much more passive. It eats very little, but is a strong fighter. It is often seen cruising through the night sky catching small bugs, partly for the fun of it.",
GameManager.pokemon.Pompet: "This little critter is an upstanding civilian. Despite its small size, it likes to help out those in need whenever it can. It has a strong heart, but needs more physical strength to do more.",
GameManager.pokemon.Pomprim: "Now big and strong, Pomprim is able to care for all creatures big and small. It likes to fly around, stopping malicious Maizotaur and Criminalis from doing their evil deeds.",
GameManager.pokemon.Saurky: "This sly little lizard can be found on beaches near the shore. It likes to make fun of smaller critters and steal their food. It finds quite a bit of joy in doing evil deeds.",
GameManager.pokemon.Crestaka: "Now bigger, this critter is able to do more evil. It likes to hold berries just out of reach of smaller critters, making them upset. Its source of anger is poor parenting.",
GameManager.pokemon.Avipex: "Now incredibly big, this bird flies up and down the shores looking for its next victim. It has learned a new move, which is simply laughing at its victims. This causes emotional damage to those who hear it.",
GameManager.pokemon.Dampurr: "Often falling victim to Crestaka's evil deeds, Dampurr is a happy cat. It likes to stay away from crowds, but enjoys occasional social interactions. They are easier to find when traveling alone.",
GameManager.pokemon.Rainther: "Now bigger and more confident, Rainther has the ability to fight off Crestaka. It also ventures further onto the beach and tries to make a few friends. It mostly keeps to itself, though.",
GameManager.pokemon.Delugar: "Now fully grown, Delugar likes to keep the Dampurr safe from Crestaka. The Dampurr enjoy seeing Delugar, as it provides protection. This critter is often found shortly after a Dampurr is found.",
GameManager.pokemon.Bonfur: "Not only is this bear incredibly adorable, it has fur that is always warm. This makes it common to snuggle during cold winter nights. Fortunately, this critter enjoys affection and welcomes any hugs.",
GameManager.pokemon.Tindursa: "Tindursa isn't quite as fond of affection as Bonfur. It lashes out if touched without warning. Its fur also heats up to unbearable temperatures during this time, so it is often left alone.",
GameManager.pokemon.Sizzly: "Now fully matured, Sizzly embraces warm hugs again. It has also gained the ability to raise and lower its body temperature at will and loves to help out. It keeps all critters warm during cold times.",
GameManager.pokemon.Lollybog: "Lollybog is a scary critter. It hides in the shadows behind big trees, scaring children and small critters that wander past. It has the ability to teleport unseen through shadows.",
GameManager.pokemon.Brewtrid: "Brewtrid has now gained the ability to possess things, commonly cauldrons. It likes the aesthetic and the space inside a cauldron. It loves to crawl out when people are cooking soup.",
GameManager.pokemon.Forbiddron: "Now fully capable of possession, Forbiddron sneaks into all sorts of objects. It still tends to return to its cauldron home often, but scares people with its possessive abilities.",
GameManager.pokemon.Kankwart: "Don't be led astray by the cute exterior of Kankwart. It has a very cute appearance, but has poisonous crystals on it. Even one small touch left untreated can be fatal. Thankfully, there is an antidote.",
GameManager.pokemon.Kankryst: "Growing into its full potential, Kankryst looks malformed. Its crystals are still incredibly poisonous, but it stays away from people. It doesn't want any critters to look at it during this stage of growth.",
GameManager.pokemon.Kankersaur: "Kankersaur is now fully evolved and has power over many critters. It has the ability to fill its crystals with poison or empty them for safe contact. It keeps the caves safe from any evildoers.",
GameManager.pokemon.Baulder: "Hiding in caves and seeing fully through echolocation, Baulder stays in the smaller parts of the caves. It eats any small things it might find, but mostly keeps to itself. It can commonly be found sleeping.",
GameManager.pokemon.Dreadrock: "Now bigger and with more mobility, Dreadrock explores further away from its small caves. This makes it easier for it to find food, and it has more social contact this way. They often make friends now.",
GameManager.pokemon.Tekagon: "Now giant, Tekagon cannot return to its small caves. It now lives throughout the full cave, but likes to stay out of the way. Still blind, it uses echolocation to look around.",
GameManager.pokemon.Minamai: "Deceptively cute, Minamai has a razor-sharp nose. One touch on the edge can cause severe bleeding. These critters are known for accidentally popping inflatable tubes. This makes many kids scared of them.",
GameManager.pokemon.Marelstorm: "Even sharper now, Marelstorm has incredibly sharp fins and a sharp nose. It is an apex predator, regardless of its size. All critters know to stay away from an angry Marelstorm, as one mistake could be fatal.",
GameManager.pokemon.Dripwirt: "Thought to be the spirit of a sailor lost at sea, Dripwirt floats around the open sea. It doesn't like to be seen and wanders around aimlessly for eternity. They seem to be sad creatures.",
GameManager.pokemon.Pourka: "Now overcoming their sadness, Pourka protects the seas. They keep sailors safe from harm and are known for controlling the weather. They want to prevent their fate from happening to others.",
GameManager.pokemon.Appalyp: "A weird little thing, Appalyp can be found deep in the sea. It likes to stay on the ocean floor, but sometimes floats up to the surface. It is unknown why this critter goes to the surface.",
GameManager.pokemon.Sycoral: "Sycoral is growing and looking even weirder. It is starting to grow various tendrils and frightens many animals away. It has a menacing aura around it that steers many clear of its path.",
GameManager.pokemon.Nemesusa: "In folklore, it is thought that if one looks at Nemesusa's tentacles, they will be turned to stone. This is, in fact, a myth. They are purely for intimidation and hunting purposes, and are quite effective.",
GameManager.pokemon.Sillennium: "A rare find, Sillennium is a guardian of the whole island. There is a group of Sillennium that keep to their posts throughout the whole island. They are normally stone, but are reanimated in times of need.",
}
